fix: label oriented bugs
CCExtractor/rutorrent-flutter pull request #107
Opened 2021-03-18 07:51 UTC by nb9960

Fixes #103

2021-03-19 14:08 UTC, rj-since-2000 requested changes

2021-03-19 16:19 UTC, nb9960 commented on lib/api/api_requests.dart
> +    if (torrentsPath.length > 0) {
Since this change resolves part one of the issue and this isn't a part of the codebase right now so I have to make this change. If the tagged PR gets merged first then I'll rebase the branch.

2021-03-25 15:04 UTC, harchani-ritik commented
@nb9960 I still see an option for "remove label" on the torrent details page of torrents with no label.

2021-03-25 15:25 UTC, nb9960 commented
> @nb9960 I still see an option for "remove label" on the torrent details page of torrents with no label.

Sorry, I pushed the last commit that used the wrong method without proper testing. Just fixed that, check once, and do let me know if everything is working fine or not. @harchani-ritik

2021-03-26 04:25 UTC, merged