Updated Status Bar Color and Created a Separate  Theme File
CCExtractor/rutorrent-flutter pull request #140
Opened 2021-05-13 11:33 UTC by 2002Bishwajeet

This PR fixes Status bar color which got merged with AppBar color and the icons were not visible clearly
Image 1: Not able to see icons clearly
![image](https://user-images.githubusercontent.com/62933155/118120096-f7818580-b40c-11eb-94f7-4cd738b73edb.png)
Image 2: The fix done
![Screenshot_20210510-204247_ruTorrent_Mobile](https://user-images.githubusercontent.com/62933155/118120080-f3556800-b40c-11eb-9848-2a98e1f530df.png)

Also Created a separate theme file and transferred all the themedata details to it (organizing the code)

2021-05-13 13:15 UTC, pratikbaid3 requested changes

2021-05-13 13:41 UTC, 2002Bishwajeet commented on lib/components/data_input.dart
> +                color: hintTextColor == null
Done 👍

2021-05-13 14:52 UTC, tusharojha approved these changes
LGTM!

2021-05-13 18:23 UTC, pratikbaid3 commented
@2002Bishwajeet on running the changes you made, this is what I get
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-13 at 23 51 38](https://user-images.githubusercontent.com/52864956/118169185-4ac3fa00-b446-11eb-92bd-9cf16c57fc88.png)

```
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building DataInput(dirty):
type 'Color' is not a subtype of type 'bool'

The relevant error-causing widget was: 
  DataInput file:///Users/pratikbaid/Desktop/Work/FlutterDev/rutorrent-flutter/lib/screens/configurations_screen.dart:162:25
When the exception was thrown, this was the stack: 
#0      DataInput.build (package:rutorrentflutter/components/data_input.dart:52:38)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4569:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4474:5)
...
====================================================================================================
```

2021-05-13 18:39 UTC, pratikbaid3 commented on lib/components/data_input.dart
> +                color: hintTextColor ?? Provider.of<Mode>(context).isLightMode
This is the cause of the issue below. What you are trying to do is evaluate a variable of type Color as a bool. Using '?.' might resolve this issue.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-13 at 23 51 38](https://user-images.githubusercontent.com/52864956/118169427-8ced3b80-b446-11eb-9ff5-75aaf177c7b6.png)

2021-05-13 18:51 UTC, 2002Bishwajeet reviewed
Ok Reverted to previous commit

2021-05-13 18:54 UTC, pratikbaid3 approved these changes

2021-05-13 19:00 UTC, pratikbaid3 commented
There are some issues in the changes you made that are causing the screen to now have a grey color instead of the original white color when the theme was set to light.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-14 at 00 29 31](https://user-images.githubusercontent.com/52864956/118173710-8e6d3280-b44b-11eb-8898-05eb664f271e.png)

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-14 at 00 29 22](https://user-images.githubusercontent.com/52864956/118173687-87debb00-b44b-11eb-900c-bf2925d695b2.png)

2021-05-13 19:06 UTC, 2002Bishwajeet commented
That's because I have set the brightness to dark  . To fix this I would have to specify background color to every widget.

Can you guide me how to get past the login screen?

2021-05-16 10:05 UTC, pratikbaid3 commented
<img src="https://user-images.githubusercontent.com/52864956/118393311-2477a780-b65c-11eb-8bda-69f6bd9406f9.png"  width="200" height="400" />

@2002Bishwajeet several issues still exist. Unfortunately, the only way to resolve them is to get a ruTorrent web running on your local machine. Please refer to the readme and the slack thread for any help

2021-05-19 23:49 UTC, rj-since-2000 requested changes
Make the necessary changes and squash your commits with appropriate messages.

2021-05-19 23:49 UTC, rj-since-2000 commented on lib/utilities/themes.dart
> +        backgroundColor: Colors.black,
The background for dark theme is too dark/black. Change it back to kBackgroundDT.

2021-05-19 23:49 UTC, rj-since-2000 commented on lib/pages/rss_feeds.dart
> +              : Colors.white,
Don't use hard coded colours like black and white, instead use the constants defined in utilities.

2021-05-20 12:17 UTC, rj-since-2000 approved these changes

2021-05-28 09:20 UTC, rj-since-2000 commented
@2002Bishwajeet fix format exceptions

2021-05-28 09:35 UTC, 2002Bishwajeet commented
@rj-since-2000  Done 👍

2021-05-28 10:21 UTC, merged