Removed Browse Torrent File option from bottom sheet in Feeds Page
CCExtractor/rutorrent-flutter pull request #49
Opened 2021-02-24 08:18 UTC by Adityabhaumik

2021-02-24 08:26 UTC, Adityabhaumik commented
@harchani-ritik could you have a look

2021-02-24 09:55 UTC, tusharojha requested changes
Hi @Adityabhaumik, 

It's great to have your contribution. I am suggesting a few changes with which we can maintain the code quality and will make it a bit more scalable. 

Although, @harchani-ritik will review the code and suggest changes if any.

2021-02-24 09:55 UTC, tusharojha commented on lib/components/add_url_bottom_sheet.dart
> +    }
No need to create a separate variable inside the build method for checking isFeed.

2021-02-24 09:55 UTC, tusharojha commented on lib/components/add_url_bottom_sheet.dart
> +            padding: EdgeInsets.only(bottom: bottomPadding),
Adding a check at this level in the widget tree seems odd because there are a lot of widgets that don't need to be rendered depending on `dialogHint`.

2021-02-24 09:55 UTC, tusharojha commented on lib/components/add_url_bottom_sheet.dart
> +                    padding: const EdgeInsets.symmetric(
You can add the check at this level. Something like:

```dart
widget.dialogHint == "Enter Rss Url" ? Container(...) : Container(),
```

2021-02-24 13:40 UTC, Adityabhaumik commented
@tusharojha thank you for the suggestion I did those changes you mentioned. Please have a look if everything is ok.

2021-02-24 13:59 UTC, tusharojha approved these changes
LGTM!

2021-02-25 00:50 UTC, merged

2021-02-25 00:51 UTC, harchani-ritik commented
Nice job @Adityabhaumik and @tusharojha :clap:

2021-02-25 01:32 UTC, Adityabhaumik commented
😀